services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: crewfare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./crewfare.sql:/docker-entrypoint-initdb.d/crewfare.sql
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./crewfare-api
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: crewfare
      PORT: 3000
    depends_on:
      - db

  frontend:
    build:
      context: ./rooming-list-app
      dockerfile: Dockerfile
      args: # <--- Use 'args' for build-time variables
        VITE_API_URL: http://api:3000/api
    restart: always
    ports:
      - "4173:4173" 
    depends_on:
      - api

volumes:
  db_data: